version: "3"
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/nginx.conf"
    ports:
      - "8000:80"
  app1:
    image: momentus-app
    environment:
      - APPID=1111
  app2:
    image: momentus-app
    environment:
      - APPID=2222
  app3:
    image: momentus-app
    environment:
      - APPID=3333
  app4:
    image: momentus-app
    environment:
      - APPID=4444
